VER_MAJOR  = 0
VER_MINOR  = 2
VER_REV    = 0
VER_STRING = f"{VER_MAJOR}.{VER_MINOR}.{VER_REV}"
VER_TUPLE  = (VER_MAJOR, VER_MINOR, VER_REV)

RELEASE_DAY   = 0
RELEASE_MON   = 0
RELEASE_YEAR  = 2025
RELEASE_TUPLE = (RELEASE_YEAR, RELEASE_MON, RELEASE_DAY)
RELEASE_STRING = f"{RELEASE_YEAR}.{RELEASE_MON}.{RELEASE_DAY}"